// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOFAnhF-H_7Ra1xoCvOxuoS5ma7kwMEmU',
    appId: '1:899775482209:web:026d9ccc41161d24695d20',
    messagingSenderId: '899775482209',
    projectId: 'login-28524',
    authDomain: 'login-28524.firebaseapp.com',
    storageBucket: 'login-28524.appspot.com',
    measurementId: 'G-VJTMC3S6G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxihFi7xmhlOltTVc-2KZm9I2hETEa3Q',
    appId: '1:899775482209:android:56a5a6102768c1f7695d20',
    messagingSenderId: '899775482209',
    projectId: 'login-28524',
    storageBucket: 'login-28524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOux010DpdNmLIZU4SgfYBqt20B62So2E',
    appId: '1:899775482209:ios:1bdbbc8b0444f7a8695d20',
    messagingSenderId: '899775482209',
    projectId: 'login-28524',
    storageBucket: 'login-28524.appspot.com',
    androidClientId: '899775482209-5hqlo52qj4de3e18cp1hfsdd62ghlv80.apps.googleusercontent.com',
    iosBundleId: 'com.example.intergrateCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOux010DpdNmLIZU4SgfYBqt20B62So2E',
    appId: '1:899775482209:ios:1bdbbc8b0444f7a8695d20',
    messagingSenderId: '899775482209',
    projectId: 'login-28524',
    storageBucket: 'login-28524.appspot.com',
    androidClientId: '899775482209-5hqlo52qj4de3e18cp1hfsdd62ghlv80.apps.googleusercontent.com',
    iosBundleId: 'com.example.intergrateCafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOFAnhF-H_7Ra1xoCvOxuoS5ma7kwMEmU',
    appId: '1:899775482209:web:834bac2c0825559e695d20',
    messagingSenderId: '899775482209',
    projectId: 'login-28524',
    authDomain: 'login-28524.firebaseapp.com',
    storageBucket: 'login-28524.appspot.com',
    measurementId: 'G-KNQ1VSL0GW',
  );
}
