// location,
//             name,
//             ownerId,
//             brNumber,
//             phone,
//             brandId,
//             image = '',
//             description = '',
//             breakTime = { start: '00:00', end: '00:00' },
//             openHour = { start: '00:00', end: '00:00' },
//             dayOffWeek = [],
